### ISSUE TITLE
PALS results empty files

### ISSUE THREAD

**Issue by dubergonzoni** [npnl/PALS#38]
Please, I need some help to understand why PALS output files are empty. 

I'm running this code with custom ROIs:

docker run -it -v /home/eduardo/Documentos/Grant/NIH/PALS/subjects:/input/ -v /home/eduardo/Documentos/Grant/NIH/PALS/results:/output/ -v /home/eduardo/Documentos/Grant/NIH/PALS/settings:/config/ -v /home/eduardo/Documentos/Grant/NIH/ALE_ROIs/:/own_rois/ amitasviper/pals:stable -d

My folders structure and files:
PALS/
 -results
 -settings/cofig.json
 -subjects/
   subj01_T1.nii
   subj01_Lesion.nii

ALE_ROIS/
  ROI1_Cluster1.nii
  ROI2_Cluster2.nii
  ROI3_Cluster3.nii
  ROI4_Cluster4.nii

My output empty csv files:
[lesion_correction_database.csv](https://github.com/npnl/PALS/files/6580157/lesion_correction_database.csv)
[lesion_load_custom_database.csv](https://github.com/npnl/PALS/files/6580159/lesion_load_custom_database.csv)

**Comment by kaoriito** [comment]
Apologies for the delayed response. Your subject directory is not set up correctly. You need a separate directory for each subject, even if you only have one subject.

PALS/
-results
-settings/cofig.json
-subjects/
-subj01/ **<--**
subj01_T1.nii
subj01_Lesion.nii

**Comment by lraguiars** [comment]
Hi @kaoriito 

Please, I need some help to understand why PALS output files are empty. I'm running this code with custom ROIs:


`(base) iMac-de-Neurovascular:Desktop neurovascularhcrp$ docker run -it -v /Users/neurovascularhcrp/Desktop/PALS_LRAS/subjects/subj01:/input/ -v /Users/neurovascularhcrp/Desktop/PALS_LRAS/results:/output/ -v /Users/neurovascularhcrp/Desktop/PALS_LRAS/settings:/config/ amitasviper/pals:stable -d
2021-11-14 18:54:36,947 INFO     Reading application configurations from file [/config/config.json]
2021-11-14 18:54:36,950 ERROR    Failed to load lesion load configs : **[Errno 2] No such file or directory: '/own_rois'
2021-11-14 18:54:36,951 DEBUG**    

2021-11-14 18:54:36,952 DEBUG    01. Radiological convention                                  :  False
2021-11-14 18:54:36,953 DEBUG    02. White Matter Correction                                  :  False
2021-11-14 18:54:36,954 DEBUG    03. Lesion Load Calculation                                  :  True
2021-11-14 18:54:36,955 DEBUG    04. Visual QC                                                :  False
2021-11-14 18:54:36,956 DEBUG    05. Pause for QC                                             :  False
2021-11-14 18:54:36,957 DEBUG    06. Input Directory                                          :  /input/
2021-11-14 18:54:36,959 DEBUG    07. Output Directory                                         :  /output/
2021-11-14 18:54:36,960 DEBUG    08. Anatomical Identifier                                    :  T1
2021-11-14 18:54:36,961 DEBUG    09. Lesion Mask Identifier                                   :  Lesion
2021-11-14 18:54:36,961 DEBUG    10. Is in same anatomical space                              :  False
2021-11-14 18:54:36,963 DEBUG    11. Is Brain Extraction Already Performed                    :  False
2021-11-14 18:54:36,964 DEBUG    12. Is White Matter Segmentation Already Performed           :  False
2021-11-14 18:54:36,965 DEBUG    13. Brain Extraction Identifier                              :  
2021-11-14 18:54:36,966 DEBUG    14. White Matter Identifier                                  :  
2021-11-14 18:54:36,967 DEBUG    15. Percent Intensity                                        :  5.0
2021-11-14 18:54:36,968 DEBUG    16. Default ROIs selected                                    :  False
2021-11-14 18:54:36,969 DEBUG    17. FreeSurfer ROIs selected                                 :  False
2021-11-14 18:54:36,969 DEBUG    18. Own ROIs selected                                        :  True
2021-11-14 18:54:36,971 DEBUG    19. Default ROIs List                                        :  []
2021-11-14 18:54:36,972 DEBUG    20. FreeSurfer ROIs List                                     :  []
2021-11-14 18:54:36,973 DEBUG    21. Own Custom ROIs List                                     :  []
2021-11-14 18:54:36,974 DEBUG    

2021-11-14 18:54:36,975 DEBUG    Stage currently executing is 0
2021-11-14 18:54:36,975 DEBUG    Selected operations initiated
2021-11-14 18:54:36,980 DEBUG    Checking for necessary files in all subject directories
2021-11-14 18:54:36,986 ERROR    
2021-11-14 18:54:36,987 DEBUG    All subjects have necessary files
2021-11-14 18:54:36,988 DEBUG    Stage currently executing is 1
2021-11-14 18:54:36,990 INFO     Creating Directories
2021-11-14 18:54:37,016 INFO     ROIs directory created successfully
2021-11-14 18:54:37,017 INFO     Gzip operation completed for all subjects
2021-11-14 18:54:37,018 INFO     Lesion file binarization initiated
2021-11-14 18:54:37,019 INFO     Lesion files of all subjects binarized successfully
2021-11-14 18:54:37,020 DEBUG    Stage currently executing is 2
2021-11-14 18:54:37,021 DEBUG    Stage currently executing is 3
2021-11-14 18:54:37,022 INFO     Brain extraction has been initiated
T1
211114-18:54:37,252 nipype.workflow INFO:
	 Workflow wf_sub settings: ['check', 'execution', 'logging', 'monitoring']
2021-11-14 18:54:37,252 INFO     Workflow wf_sub settings: ['check', 'execution', 'logging', 'monitoring']
211114-18:54:37,306 nipype.workflow INFO:
	 Running in parallel.
2021-11-14 18:54:37,306 INFO     Running in parallel.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/PALS/utils/operations.py", line 110, in startExecution
    self.runBrainExtraction(self.anatomical_id, self.lesion_mask_id)
  File "/PALS/utils/brain_extraction_operation.py", line 23, in runBrainExtraction
    bet_id = runNipypeBet(self.controller, self.subjects, anatomical_id, projBaseDir)
  File "/PALS/utils/brain_extraction_workflow.py", line 51, in runNipypeBet
    wf_sub.run(plugin='MultiProc')
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/workflows.py", line 599, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/base.py", line 122, in run
    self._generate_dependency_list(graph)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/base.py", line 401, in _generate_dependency_list
    self.depidx = nx.to_scipy_sparse_matrix(graph, nodelist=self.procs)
  File "/usr/local/lib/python2.7/dist-packages/networkx/convert_matrix.py", line 765, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
NetworkXError: Graph has no nodes or edges`

Why didn't PALS recognize ROIs?
Thank you very much!

Best,
LRAS.
